---
name: Perl6-GatherTake
version: 0.0.3
author:
  - Moritz Lenz
abstract: 'Perl 6 like gather { .. take } blocks'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Coro: 1.0
  Scalar::Util: 0
  perl: 5.6.1
provides:
  Perl6::GatherTake:
    file: lib/Perl6/GatherTake.pm
    version: 0.0.3
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
